# Generated by Django 4.1.3 on 2022-11-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agendaDisponiblePorMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=40)),
                ('horario', models.DateTimeField()),
                ('tarde_mañana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('matricula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('obraSocial', models.CharField(max_length=40)),
                ('fechaNacimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='paciturnoReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('medico', models.CharField(max_length=40)),
                ('obraSocial', models.CharField(max_length=40)),
                ('Dia', models.DateField()),
            ],
        ),
    ]
