# Generated by Django 4.1.3 on 2022-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agendaDisponiblePorMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=40)),
                ('dia', models.DateField()),
                ('hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dedicacion', models.CharField(max_length=40)),
                ('matricula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('obraSocial', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
                ('fechaNacimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='turnoReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('medico', models.CharField(max_length=40)),
                ('obraSocial', models.CharField(max_length=40)),
                ('Dia', models.DateField()),
            ],
        ),
    ]
