# Generated by Django 4.1.3 on 2022-12-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendadisponiblepormedico',
            name='desde',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dia/hora'),
        ),
        migrations.AlterField(
            model_name='agendadisponiblepormedico',
            name='hasta',
            field=models.TimeField(blank=True, null=True, verbose_name='tiempo'),
        ),
    ]
