# Generated by Django 4.1.3 on 2022-11-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paciturnoReservado',
            new_name='turnoReservado',
        ),
    ]
