# Generated by Django 4.1.3 on 2022-12-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendadisponiblepormedico',
            name='hora',
        ),
        migrations.AddField(
            model_name='agendadisponiblepormedico',
            name='tarde_mañana',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
