# Generated by Django 4.1.3 on 2022-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0002_remove_agendadisponiblepormedico_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendadisponiblepormedico',
            name='dia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agendadisponiblepormedico',
            name='tarde_mañana',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='turnoreservado',
            name='Dia',
            field=models.DateTimeField(),
        ),
    ]
