# Generated by Django 4.1.3 on 2022-12-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0002_rename_paciturnoreservado_turnoreservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='DNI',
            field=models.IntegerField(default=22430186),
            preserve_default=False,
        ),
    ]
