# Generated by Django 4.1.3 on 2022-12-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0002_rename_paciturnoreservado_turnoreservado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(max_length=40)),
            ],
        ),
    ]
