# Generated by Django 4.1.3 on 2022-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0003_remove_agendadisponiblepormedico_dia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=40)),
                ('desde', models.DateTimeField(blank=True, null=True, verbose_name='Dia / Desde hora')),
                ('hasta', models.TimeField(blank=True, null=True, verbose_name='Hasta hora')),
            ],
        ),
        migrations.DeleteModel(
            name='agendaDisponiblePorMedico',
        ),
    ]
