# Generated by Django 4.1.3 on 2022-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0004_alter_agendadisponiblepormedico_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendadisponiblepormedico',
            name='tarde_mañana',
        ),
        migrations.AddField(
            model_name='agendadisponiblepormedico',
            name='desde',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendadisponiblepormedico',
            name='hasta',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
