# Generated by Django 4.1.3 on 2022-12-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0005_alter_turnoreservado_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoreservado',
            name='Dia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dia / horario'),
        ),
    ]
