# Generated by Django 4.1.3 on 2022-12-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0007_turno_delete_turnoreservado'),
    ]

    operations = [
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('medico', models.CharField(max_length=40)),
                ('obraSocial', models.CharField(max_length=40)),
                ('Dia', models.DateTimeField(blank=True, null=True, verbose_name='Dia / horario')),
            ],
        ),
        migrations.DeleteModel(
            name='turno',
        ),
    ]
