# Generated by Django 4.1.3 on 2022-12-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0010_rename_agenda_agendas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='DNI',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='turnos',
            name='paciente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppTurnos1.pacientes'),
            preserve_default=False,
        ),
    ]
