# Generated by Django 4.1.3 on 2022-12-31 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0011_remove_turnos_dni_remove_turnos_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='medico',
        ),
        migrations.AddField(
            model_name='turnos',
            name='agenda',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppTurnos1.agendas'),
            preserve_default=False,
        ),
    ]
