# Generated by Django 4.1.3 on 2022-12-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnos1', '0012_remove_turnos_medico_turnos_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='Dia',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='obraSocial',
        ),
        migrations.AddField(
            model_name='turnos',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hasta hora'),
        ),
    ]
